config/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Expressways Administration'
admin.site.site_title = 'Expressways Administration'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('expressways.core.urls', namespace='core')),
]

expressways/core/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500

from expressways.core.views import (HomeView,
                                    DeleteOccurrenceConfiguration,
                                    CalculateView,
                                    ResultView,
                                    RoadSelectionView)

app_name = 'core'
urlpatterns = [
    path('', RoadSelectionView.as_view(), name='road'),
    path('home/<int:road_id>', HomeView.as_view(), name='home'),
    path('delete/<int:pk>', DeleteOccurrenceConfiguration.as_view(), name='delete'),
    path('calculate', CalculateView.as_view(), name='calculate'),
    path('result/<str:task_id>', ResultView.as_view(), name='result'),
]

handler404 = 'expressways.core.views.custom404'
handler500 = 'expressways.core.views.custom500'

expressways/core/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _


class FilterArchivedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(archived=True).order_by('id')


class CommonInfo(models.Model):
    name = models.CharField(max_length=200, help_text=_('Provide a short, descriptive name'))
    archived = models.BooleanField(default=False)

    objects = FilterArchivedManager()

    class Meta:
        abstract = True


class Occurrence(CommonInfo):
    def __str__(self):
        return self.name


class SubOccurrence(CommonInfo):
    occurrence = models.ForeignKey(
        Occurrence,
        on_delete=models.CASCADE,
        help_text=_('Select ‘parent’ occurrence for the new sub-occurrence e.g. spillage (sub-occurrence) > Debris in road (parent occurrence). Add new occurrence if required.'),
        related_name='sub_occurrences'
    )

    def __str__(self):
        return self.name


class DesignComponent(CommonInfo):
    description = models.TextField(
        help_text=_('Provide a description of the design component, including any relevant references or supporting information')
    )

    def __str__(self):
        return self.name


class Road(CommonInfo):
    def __str__(self):
        return self.name
    

LANE_CHOICES = (
    ('II', 'II'),
    ('XI', 'XI'),
    ('XX', 'XX'),
    ('S', 'S'),
)

DURATION_CHOICES = (
    (0.0, '0'),
    (2.5, '2.5'),
    (10.0, '10'),
    (25.0, '25'),
    (45.0, '45'),
    (90.0, '90'),
)

FLOW_CHOICES = (
    ('High', 'High'),
    ('Medium', 'Medium'),
    ('Low', 'Low'),
)

SPEED_CHOICES = (
    (70, '70'),
    (60, '60'),
    (50, '50'),
    (40, '40'),
)

class OccurrenceConfiguration(models.Model):
    road = models.ForeignKey(
        Road,
        help_text=_('Select road/project name​'),
        on_delete=models.CASCADE,
        null=True,
    )
    sub_occurrence = models.ForeignKey(
        SubOccurrence, 
        help_text=_('Select sub-occurrence to edit, re-name the sub-occurrence or create a new entry​'),
        on_delete=models.CASCADE
    )
    lane_closures = models.CharField(
        help_text=_('Select lane impact parameters i.e. II = all lanes open, XI = one lane closed (lane one or two), XX = both lanes closed, S = slow moving vehicle or WCH in lane​'),
        verbose_name='impact',
        max_length=2,
        choices=LANE_CHOICES,
        default='II',
    )
    duration = models.FloatField(
        help_text=_('Select how long the incident occurs for. i.e. 2.5 = 0 to 5 minutes; 10 = 5 to 15 minutes; 25 = 15 to 30 minutes; 45 = 30 to 60 minutes; 90 = 60 to 120 minutes. Not required for "slow moving vehicle" or "all lanes open" incident.'),
        choices=DURATION_CHOICES,
        default=2.5,
    )
    flow = models.CharField(
        help_text=_('Select traffic flow condition: High = >1000 Medium = >400 <1000 Low = <400 (vph)​'),
        verbose_name='flow rate',
        max_length=20,
        choices=FLOW_CHOICES,
        default='Low',
    )
    speed_limit = models.PositiveIntegerField(
        help_text=_('Select prevailing traffic speed (mph) for given occurrence (set default to 70mph)​​'),
        choices=SPEED_CHOICES,
        default=70,
    )
    frequency = models.PositiveIntegerField(
        help_text=_('Define the frequency of the occurrence (average per 1000 miles per year)​')
    )
    incidents_cleared = models.BooleanField(
        help_text=_('If ticked, incidents occurring as a result of this Operational Occurrence will be included in the ‘Incidents Cleared’ calculation (as defined by the "IncidentClearance" field code in ControlWorks data)'),
        default=False
    )
    references = models.TextField(
        help_text=_('Provide references to data sources or a detailed explanation of any assumptions used e.g. calculations to determine frequencies or durations.'),
        default=''
    )
    effect = models.ManyToManyField(
        DesignComponent,
        verbose_name='Possible intervention',
        through='EffectIntervention'
    )

    def __str__(self):
        return f'{self.sub_occurrence.name}, {self.lane_closures}, {self.duration}, {self.flow}, {self.frequency}' 


class EffectIntervention(models.Model):
    design_component = models.ForeignKey(
        DesignComponent, 
        help_text=_('Select design component to create an impact score​'),
        on_delete=models.CASCADE, 
        verbose_name='Design component',
        null=True,
    )
    configuration_effect = models.ForeignKey(
        OccurrenceConfiguration,
        on_delete=models.CASCADE,
        verbose_name='Effect on configuration',
        null=True,
    )
    frequency_change = models.IntegerField(
        help_text=_(f'% change in frequency'),
        validators=[MinValueValidator(-100)],
        verbose_name='Frequency change (%)',
    )
    duration_change = models.IntegerField(
        help_text=_(f'% change in duration'),
        validators=[MinValueValidator(-100)],
        verbose_name='Duration change (%)',
    )
    justification = models.TextField(
        help_text=_('Provide a detailed explanation and references for the sources of the impact sources. Must be based on real data, published research or an assumption agreed with relevant subject matter experts')
    )

    def __str__(self):
        return f'{self.design_component.name} with {self.frequency_change}% frequency and {self.duration_change}% duration change'


class OperationalObjective(CommonInfo):
    description = models.TextField()
    identifier = models.CharField(
        help_text=_('Operational objective identifier​'),
        max_length=10,
        default='',
    )

    def __str__(self):
        return self.name

expressways/core/forms.py
from django.forms import Form, ModelChoiceField, ModelMultipleChoiceField, ValidationError
from django.forms.widgets import CheckboxSelectMultiple
from django.utils.translation import ugettext_lazy as _

from expressways.core.models import Road, DesignComponent


class RoadSelectionForm(Form):
    road = ModelChoiceField(
        queryset=Road.objects.all(), 
        label='', 
        empty_label=None
    )

class InterventionForm(Form):   
    design_components = ModelMultipleChoiceField(
        queryset=DesignComponent.objects.all(),
        widget=CheckboxSelectMultiple(attrs={'class': 'custom-control-input'}),
        required=False
    )

    def clean_design_components(self):
        data = self.cleaned_data['design_components']
        vms = DesignComponent.objects.get(pk=4) # for VMS design component
        tos = DesignComponent.objects.get(pk=3) # for Traffic Officer design component
        if vms in data and tos not in data:
            raise ValidationError(
                _(f'{vms.name} has to be selected together with {tos.name}'),
                code='invalid'
            )
        return data
                

expressways/core/views.py
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, FormView
from django.views.defaults import page_not_found, server_error
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from braces.views import LoginRequiredMixin
from celery.result import AsyncResult

from expressways.calculation.models import CalculationResult
from expressways.calculation.tasks import calculate
from expressways.core.models import OccurrenceConfiguration, Occurrence, SubOccurrence, Road, DesignComponent, EffectIntervention, OperationalObjective
from expressways.core.forms import InterventionForm, RoadSelectionForm


class HomeView(LoginRequiredMixin, View):
    def get(self, request, road_id):
        try:
            road = Road.objects.get(id=road_id)        
        except Road.DoesNotExist:
            return render(request, '404.html', { 'message': 'The road does not exist.' })
        
        form = InterventionForm()
        configurations = OccurrenceConfiguration.objects.filter(road=road_id)
        objectives = OperationalObjective.objects.all()
        context = {
            'road': road,
            'objectives': objectives,
            'configurations': configurations,
            'form': form,
        }
        return render(request, 'core/home.html', context)


class DeleteOccurrenceConfiguration(LoginRequiredMixin, DeleteView):
    model = OccurrenceConfiguration

    def get_object(self):
        obj = super(DeleteOccurrenceConfiguration, self).get_object()
        CalculationResult.objects.filter(config_ids__contains=[obj.pk]).delete()
        return obj

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        if 'task_id' in self.request.session:
            del self.request.session['task_id']
        return response

    def get_success_url(self):
        return reverse('core:home', kwargs={'road_id': self.request.session['road_id']})


class CalculateView(LoginRequiredMixin, View):
    road_id = None

    def post(self, request):
        self.road_id = request.session['road_id']
        form = InterventionForm(request.POST)

        if form.is_valid():
            components = form.cleaned_data['design_components'] 
            if components:
                request.session['task_id'] = self.process_expressways_calculation(components)
            else:
                request.session['task_id'] = self.process_baseline_calculation()
            
        configurations = OccurrenceConfiguration.objects.filter(road=self.road_id)
        road = Road.objects.get(id=self.road_id)
        objectives = OperationalObjective.objects.all()
        context = {
            'road': road,
            'objectives': objectives,
            'configurations': configurations,
            'form': form,
        }
        return render(request, 'core/home.html', context)

    def create_calculation_object(self, occ_config):
        return {
            'lane_closures': occ_config.lane_closures,
            'duration': occ_config.duration,
            'flow': occ_config.flow,
            'speed': occ_config.speed_limit,
            'frequency': occ_config.frequency,
            'incidents_cleared': occ_config.incidents_cleared
        }
    
    def process_baseline_calculation(self):
        items = []
        calc_ids = []
        for item in OccurrenceConfiguration.objects.filter(road=self.road_id):
            calc_ids.append(item.pk)            
            if (item.frequency == 0):
                continue

            items.append(self.create_calculation_object(item))

        try:
            calculated = CalculationResult.objects.get(config_ids=calc_ids, component_ids=[])
            return calculated.task_id
        except CalculationResult.DoesNotExist:
            res = calculate.delay(calc_ids, items)
            return res.id

    def create_expressways_object(self, occ_config, freq_val, dur_val):
        return {
            'lane_closures': occ_config.lane_closures,
            'duration': occ_config.duration,
            'flow': occ_config.flow,
            'speed': occ_config.speed_limit,
            'frequency': occ_config.frequency,
            'incidents_cleared': occ_config.incidents_cleared,
            'duration_change': (dur_val / 100),
            'frequency_change': (freq_val / 100)
        }

    def value_to_use(self, value_list: list):
        if len(value_list) == 0:
            return 0
        max_val = max(value_list)
        min_val = min(value_list)
        if max_val > 0:
            return max_val
        else:
            return min_val

    def process_expressways_calculation(self, components):
        items = []
        calc_ids = []
        comp_ids = []
        freq_list = []
        dur_list = []
        for occ_config in OccurrenceConfiguration.objects.filter(road=self.road_id):
            calc_ids.append(occ_config.pk)            
            for comp in components:
                comp_ids.append(comp.pk)
                for item in EffectIntervention.objects.filter(configuration_effect__pk=occ_config.pk, design_component__pk=comp.pk):
                    freq_list.append(item.frequency_change) 
                    dur_list.append(item.duration_change)

            marked_freq_val = self.value_to_use(freq_list)
            marked_dur_val = self.value_to_use(dur_list)  
            if (occ_config.frequency == 0) or (occ_config.duration == 0.0 and marked_dur_val < 0):
                continue
            items.append(self.create_expressways_object(occ_config, marked_freq_val, marked_dur_val))  

        try:
            calculated = CalculationResult.objects.get(config_ids=calc_ids, component_ids=comp_ids)
            return calculated.task_id
        except CalculationResult.DoesNotExist:
            res = calculate.delay(calc_ids, items, comp_ids)
            return res.id


class ResultView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        res = AsyncResult(task_id)
        if res.state == 'APP':
            return JsonResponse({'msg': res.result["msg"]}, status=500)

        if res.failed():
            return JsonResponse({'msg': 'The Task Failed'}, status=500)

        result = get_object_or_404(CalculationResult, task_id=task_id)

        # We need to ensure the worker frees the resources when receiving a result
        # otherwise the resources (memory) will continue to increase.

        # See documentation:

        # Warning: Backends use resources to store and transmit results. To ensure that
        # resources are released, you must eventually call get() or forget() on EVERY
        # AsyncResult instance returned after calling a task.
        res.forget()
        
        obj = {
            'objective_incident': '-',
            'objective_pti': '-',
            'objective_journey': '-',
            'objective_speed': '-',
            'objective_exp_incident': '-',
            'objective_exp_pti': '-',
            'objective_exp_journey': '-',
            'objective_exp_speed': '-'
        }
        if 'result' in request.session:
            obj = request.session['result']

        if len(result.component_ids) > 0:
            obj['objective_exp_incident'] = str(result.objective_incident)
            obj['objective_exp_pti'] = str(result.objective_pti)
            obj['objective_exp_journey'] = str(result.objective_journey)
            obj['objective_exp_speed'] = str(result.objective_speed)
        else:
            obj['objective_incident'] = str(result.objective_incident)
            obj['objective_pti'] = str(result.objective_pti)
            obj['objective_journey'] = str(result.objective_journey)
            obj['objective_speed'] = str(result.objective_speed)

        request.session['result'] = obj 

        return JsonResponse({
            'objective_incident': obj['objective_incident'], 
            'objective_pti': obj['objective_pti'], 
            'objective_journey': obj['objective_journey'],
            'objective_speed': obj['objective_speed'],
            'objective_exp_incident': obj['objective_exp_incident'], 
            'objective_exp_pti': obj['objective_exp_pti'], 
            'objective_exp_journey': obj['objective_exp_journey'],
            'objective_exp_speed': obj['objective_exp_speed']
        })


class RoadSelectionView(LoginRequiredMixin, FormView):
    template_name = 'core/road_selection.html'
    form_class = RoadSelectionForm
    road_id = None

    def get_initial(self):
        initial = super(RoadSelectionView, self).get_initial()
        if 'road_id' in self.request.session:
            initial['road'] = Road.objects.get(id=self.request.session['road_id'])
        return initial

    def form_valid(self, form):
        road = form.cleaned_data.get('road')
        self.road_id = road.id
        return super(RoadSelectionView, self).form_valid(form)

    def get_success_url(self):
        self.request.session['road_id'] = self.road_id
        if 'task_id' in self.request.session: # reset any previous task id when road is changed
            del self.request.session['task_id']
        if 'result' in self.request.session: # reset any previous calculation result
            del self.request.session['result']
        return reverse('core:home', kwargs={'road_id': self.road_id})


def custom404(request, exception=None):
    return page_not_found(request, None, '404.html')

def custom500(request):
    return server_error(request, '500.html')

expressways/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "base.css" %}">
    {% block extrahead %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg transparent">
      <a href="/" class="navbar-brand">
        <div class="logos">
          <img src="{% static 'img/expressways-logo.png' %}" alt="Expressways Logo">
          <div><span class="navbar-text">Expressways</span></div>
        </div>
      </a>
      {% if not request.user.is_anonymous %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><span class="navbar-text">Hello, {{request.user.username}}</span></li>
        {% if request.user.is_staff %}
        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href="{% url 'password_change' %}">Change Password</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
      </ul>
      </div>
      {% endif %}
    </nav>
    <br>

    <div class="container">
  {% block content %}
  {% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.4/js/mdb.min.js"></script>
    <script src="{% static "base.js" %}"></script>
  </body>
</html>

expressways/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block extrahead %}
  {% if request.session.task_id %}
    <script>
      var result_url = "{% url 'core:result' request.session.task_id %}";
    </script>
  {% endif %}
{% endblock %}

{% block content %}
  <div id="road-header">
    <div class="row col-name">Selected road:</div>
    <div id="road-name" class="row">{{ road.name }}</div>
    <div class="row small"><a href="{% url 'core:road' %}">back to road selection</a></div>
  </div>
  <div class="row">
    <div class="col">
      <div id="error-card" class="card red accent-2" style="display: none;">
        <div class="card-body white-text">
          <span class="card-title">An Error Occurred</span>
          <p id="error-msg"></p>
          <p>Please try again later</p>
        </div>
      </div>
    </div>
  </div>
  <section id="calculation" class="container-fluid">
    <form class="d-flex flex-column" method="POST" action="{% url 'core:calculate' %}">
      {% csrf_token %}
      <div class="row">
        <h2>Design Components</h2>
      </div>
      <div class="row">
        <p class="pb-2">Click on the design component(s) to analyse. Note, VMS must have Traffic Officers enable to realise all the benefits of the service.​</p>
      </div>
      <div class="row">
        {% for comp in form.design_components %}
        <div class="col-lg-3 col-md-6 col-sm-12">
          <div class="custom-switch">
            {{ comp.tag }}
            <label class="custom-control-label" for="{{ comp.id_for_label }}">{{ comp.choice_label }}</label>
          </div>
        </div>
        {% endfor %}
      </div>
      {% if form.design_components.errors %}
      <div class="row card red accent-2">
        <div class="card-body white-text">
          <p>Error: {{ form.design_components.errors.as_text }}</p>
        </div>
      </div>
      {% endif %}
      <button id="calculate_btn" type="submit" class="btn green accent-3 align-self-end">Calculate Results</button>
    </form>
  </section>
  <section id="objective-area">
    <div class="row mt-2">
      <div class="col-6">
      </div>
      <div class="col-3">
        <h2 class="text-center">Baseline result</h2>
      </div>
      <div class="col-3">
        <h2 class="text-center">Expressways result</h2>
      </div>
    </div>
    {% for objective in objectives %}
    <div class="row">
      <div class="col-6">
        <h2>{{ objective.name }}</h2>
        <p>{{ objective.description }}</p>
      </div>
      <div class="col result align-self-center">
        <div id="result-{{ objective.identifier }}">-</div>
      </div>
      <div class="col result align-self-center">
        <div id="result-exp-{{ objective.identifier }}">-</div>
      </div>
    </div>
    {% endfor %}
  </section>

  <div id="spinner" class="modal fade">
    <div class="modal-dialog modal-sm">
      <h4 class="modal-title">Loading Results</h4>
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
  </div>
{% endblock %}

expressways/core/templates/core/road_selection.html
{% extends 'core/base.html' %}

{% block content %}
<p>Select a road:</p>
<form class="d-flex flex-column" method="POST">
  {% csrf_token %}
  {{form}}
  <br>
  <button type="submit" class="btn green accent-3 align-self-end">Start Analysis</button>
</form>
{% endblock %}